name: Make a request to Render every 14 minutes

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  render-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Products
        run: curl https://poc-medusa-server.onrender.com/store/products
